### PR TITLE
Updating buildnipkg for RoboRIO 2.0

### PR DESCRIPTION
**Pull request by marshallmassengill**
Updated buildnipkg to resolve boot script issue for RoboRIO 2.0 kernel builds.  Updated script contents derived from RoboRIO 2.0 image provided by NI for FRC testing/usage.

### CODE REVIEW

**Comment by gratian** [comment]
Thanks @marshallmassengill, the PR is appreciated. I have not done an in-depth review of the changes yet but there are a couple commit formatting suggestions I would like to quickly point out.

In our ni/linux branches we are trying to follow the upstream kernel formatting and process for commits described in: https://github.com/ni/linux/blob/nilrt/master/4.14/Documentation/process/submitting-patches.rst

In particular can you make sure you follow the following sections in that document:
  2) Describe your changes
  3) Separate your changes
  11) Sign your work - the Developer's Certificate of Origin
  
Formatting the commit with a subject line:

- subsystem: summary phrase
- an empty line.
- the body of the explanation, line wrapped at 75 columns
- the Signed-off-by: <>

would also be appreciated. It seems nit-picky but it keeps our git history clean and parsable. This is described in the section "14) The canonical patch format" of the document linked above.
You can obviously ignore the parts in that document that talk about emailing stuff.

At a quick glance I can see the following independent logical changes/commits in your PR (it doesn't matter if a change is just one line):

- the bootargs change to support booting from sd cards;
- the usb host/device switching;
- the wireless region switching;
- custom boot message;
- setting the manufacturer variable.

See other existing commits for inspiration.

**Comment by gratian** [comment]
@jhershbe your review would be appreciated.

**Comment by marshallmassengill** [comment]
Thanks @gratian.  I'm happy to do what I can for this and I'll try and provide some of that in a cleanup commit but it might make more sense for that level of detail to come from the original developer.  I'm not sure who that is.  This is purely a fix on my part so it's possible there is additional work that needs to be done that I'm just not aware of.  The changes came from NI and were sourced from the bootscript file pulled from a working image.

**Comment by gratian** [comment]
Thanks @marshallmassengill. We're working on looping in the right people for RoboRIO 2.0 from the NI side.

**Comment by marshallmassengill** [comment]
Looks like this is being resolved with this: https://github.com/ni/linux/pull/51

I'm going to close this pull request.  Thanks folks!

**Pull request closed without merging**
