### PR TITLE
usb: dwc3: pci: skip BYT GPIO lookup table for hardwired phy

### PR DESCRIPTION
**Pull request by gratian**
Hardware based on the Bay Trail / BYT SoCs require an external ULPI phy for USB device-mode. The phy chip usually has its 'reset' and 'chip select' lines connected to GPIOs described by ACPI fwnodes in the DSDT table.

Because of hardware with missing ACPI resources for the 'reset' and 'chip select' GPIOs commit 5741022cbdf3 ("usb: dwc3: pci: Add GPIO lookup table on platforms without ACPI GPIO resources") introduced a fallback gpiod_lookup_table with hard-coded mappings for Bay Trail devices.

However there are existing Bay Trail based devices, like the National Instruments cRIO-903x series, where the phy chip has its 'reset' and 'chip-select' lines always asserted in hardware via resistor pull-ups. On this hardware the phy chip is always enabled and the ACPI dsdt table is missing information not only for the 'chip-select' and 'reset' lines but also for the BYT GPIO controller itself "INT33FC".

With the introduction of the gpiod_lookup_table initializing the USB device-mode on these hardware now errors out. The error comes from the gpiod_get_optional() calls in dwc3_pci_quirks() which will now return an -ENOENT error due to the missing ACPI entry for the INT33FC gpio controller used in the aforementioned table.

This hardware used to work before because gpiod_get_optional() will return NULL instead of -ENOENT if no GPIO has been assigned to the requested function. The dwc3_pci_quirks() code for setting the 'cs' and 'reset' GPIOs was then skipped (due to the NULL return). This is the correct behavior in cases where the phy chip is hardwired and there are no GPIOs to control.

Since the gpiod_lookup_table relies on the presence of INT33FC fwnode in ACPI tables only add the table if we know the entry for the INT33FC gpio controller is present. Additionally check the 'cs' gpio handle is not NULL before using it (like we do for the 'reset' line). This allows Bay Trail based devices with hardwired dwc3 ULPI phys to continue working.

Fixes: 5741022cbdf3 ("usb: dwc3: pci: Add GPIO lookup table on platforms without ACPI GPIO resources")

### CODE REVIEW

**Comment by gratian** [comment]
### Testing

- locally built new 6.1-rt kernel and installed on two cRIO-903x targets cross connected over USB. One of the targets has the old BIOS with the missing GPIO controller information the other one has the updated BIOS
- verified that the USB ethernet interface comes up correctly on both targets
- verified that I can connect in both directions between these targets over the USB device connection

**Comment by gratian** [comment]
### Note for reviewers

- I'm going to try to submit this upstream so I would appreciate feedback on the commit message itself in addition to the code.

**Review by chaitu236 — APPROVED** [review]
Both code change and description look good to me.

**Comment by gratian** [comment]
Tweaked the patch subject line to fit within the kernel patches max subject line rules.

**Review by bstreiff — APPROVED** [review]

**Comment by gratian** [comment]
Made the subject line (even) shorter to avoid wrapping in the email for upstream.

**Pull request merged**
