### PR TITLE
Enabled features in nati_x86_64_defconfig

### PR DESCRIPTION
**Pull request by joergho**
Add the following features in nati_x86_64_defconfig:

- iptables NAT support (incl. optional features)
- SCTP protocol (incl.optional features)
- HugeTLB file system support

### CODE REVIEW

**Review by gratian — COMMENTED** [review]
I think this fixup commit can be dropped. The compressed defconfig format generated via 'make savedefconfig' will drop configuration options that can be deduced from other selected options. From what I can tell that's the case with 'CONFIG_RANDOM_TRUST_CPU'.
Otherwise the PR looks good.

**Review by gratian — COMMENTED** [review]
Actually I've missed something in my previous comment: can you make sure the commit message follows Linux kernel guidelines. In particular it is currently missing your sign-off in addition to formatting issues.

The commit message needs:

- a short subject line starting with `nati_x86_64_defconfig:`
- an empty line
- a description/explanation why the changes are needed wrapped at 75 columns. Please make sure you describe the 'Why' not the 'What changed'.
- an empty line
- a `Signed-off-by: <your name/email>`

You can model it after other commits like:

- https://github.com/ni/linux/pull/68/commits/75ec5472703f73df779929a344896fa6deecd57b
- https://github.com/ni/linux/pull/70/commits/e5488637946667a570b8e955d7c1e97702b8d06b

**Comment by joergho** [comment]
Hi @gratian, I have addressed your comments.

**Review by gratian — APPROVED** [review]
The commit message is still not quite up to (upstream) kernel standards but I think I can tweak it from here. Thanks.

**Comment by gratian** [comment]
Commit message re-worked an submitted as commit 50efd70c0c579cfb53935ffd8e5a9d940a2c390e ("nati_x86_64_defconfig: enable features for HPC applications")

**Pull request closed without merging**
