### PR TITLE
Upgrade 'next' development nilrt kernel from 5.10 to 5.14

### PR DESCRIPTION
**Pull request by gratian**
This is a rebase of our kernel commits on top of [linux-rt-devel/v5.14-rt16](https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/tag/?h=v5.14-rt16).

Additional clean-up done during rebase:

- squashed all previous nati_x86_64_defconfig commits into one. Their number was getting out of hand and it unnecessarily complicates rebases and bisects. I've retained the commit messages for traceability.
- squashed tracing fix-up commits accumulated while performing 5.10 stable updates:
```
pick ccacc5f3499b ftrace: ni: add raw marker support for trace tool
squash 43b183edabfa tracing: ni: Update tracing_ni_ett_raw_write per upstream internal API changes
squash 3fbbc9cd50a4 tracing: ni: Update tracing_ni_ett_raw_write for upstream internal API changes
squash 34722177db74 tracing: ni: Use always_inlined __trace_buffer_lock_reserve()
```
- (re)grouped our commits by the subsystem they affect.

During the rebase the following conflicts were resolved in-place:

- https://github.com/ni/linux/commit/62ecc94e06bbba333821850684280a79e6fa6ab8 ("shared: Adding mcopy syscall for x64") -  update syscall numbers to account for upstream additions; dropped arm bits
- https://github.com/ni/linux/commit/3996c32532c1350a98f4e785cea33111f029533e ("irq: Add priority support to /proc/irq/../ ") -  convert MAX_USER_RT_PRIO to MAX_RT_PRIO following commit ae18ad281e82 ("sched: Remove MAX_USER_RT_PRIO")

Testing

- [x] Audited config changes and identified one option that required commit https://github.com/ni/linux/commit/713329500cb30fc974f4b24abbbaaafffedc69c2 ("nati_x86_64_defconfig: disable CONFIG_SLUB_CPU_PARTIAL")
- [x] Boot tested on cRIO-9035, cRIO-9043, cRIO-9049, PXIe-8880
- [x] Verified that major peripherals like ethernet and serial work.
- [x] Ran kernel-performance-tests ptest and verified that the cyclictest performance numbers with various loads across the hardware listed above shows comparable or better performance when compared to nilrt/master/5.10

[procedural note: We will want to complete this pull request outside the github UI to create the proper nilrt/master/5.14 branch]

### CODE REVIEW

**Comment by gratian** [comment]
FYI: @ni/rtos

**Comment by bstreiff** [comment]
Squashing the defconfig for a fresh start on 5.14 feels like a good idea. I'm not sure that it needs a gigantic commit message with the full history-- that history remains in the past branches, and the patch rework comments and other comments like "upgrade from 5.6 to 5.10" don't make much sense in a squashed context. If you want to do it that way that's fine though.

**Review by bstreiff — APPROVED** [review]

**Comment by gratian** [comment]
Yeah. I went back and forth if I should keep all the defconfig commit messages. I think I agree with you - it makes the log unwieldy so I'll reword the gigantic commit message and drop the individual change descriptions.

**Comment by gratian** [comment]
Cleaned-up the defconfig log as commented above and pushed this branch as nilrt/master/5.14.

**Pull request closed without merging**
