### PR TITLE
Upgrade 'next' NILRT development kernel from 5.19-rt to 6.0-rt

### PR DESCRIPTION
**Pull request by gratian**
This is a rebase of our commits from nilrt/master/5.19 to the latest devel-rt/linux-6.0.y-rt branch.

During the rebase the following commits were resolved in place:

- e42adb376ae3 ("nirtfeatures: Added NI RT features driver"): fix trivial conflict with 6c93c6f3bad4 ("misc: Add a mechanism to detect stalls on guest vCPUs")
- 4d8be1363cbd ("Revert "time: Always make sure wall_to_monotonic isn't positive""): fix conflict with b8ac29b40183 ("timekeeping: contribute wall clock to rng on time change")

Additional fixes:
- Commit 145e8921120b ("8250_ni16550: pass termios as param to ni16550_config_rs485") was added due to commit ae50bb275283 ("serial: take termios_rwsem for ->rs485_config() & pass termios as param") which changed the signature of the rs485_config callback.

Additional clean-up:
- squashed all accumulated defconfig changes in commit 84c7e194024c ("nati_x86_64_defconfig: defconfig for NI x86_64-based targets")
- commit d0e236dcb51b ("8250_ni16550: fix compiler warning about mixed declarations and code") was added to fix a compiler warning

Testing:

- [x] boot tests on representative set of controllers
- [x] .config audit
- [x] dmesg audit
- [x] basic peripheral functionality validation
- [x] OS level kernel performance tests

[procedural note: We will want to complete this pull request outside the github UI to create the proper nilrt/master/6.0 branch]

### CODE REVIEW

**Review by bstreiff — COMMENTED** [review]
The resolves and fixes you've called out seem fine (d0e236d was also on my radar already in the 8250 stuff).

It does look like the defconfig is dropping some EFI-related tokens vs. 5.15 though:
```
242,243c237
< CONFIG_EFI_VARS=y
< CONFIG_EFI_RUNTIME=y
---
> # CONFIG_EFI_DISABLE_RUNTIME is not set
```

**Comment by gratian** [comment]
I've dropped our out-of-tree commit 87e635c01011b499290e1572996d26dc817aa755 ("drivers/firmware/efi/Kconfig: Add EFI_RUNTIME") in favor of upstream commit a031651ff2144a3d81d4916856c093bc1ea0a413 ("efi: Allow to enable EFI runtime services by default on RT"). This was done in the previous 5.19-rt upgrade PR: https://github.com/ni/linux/pull/72

The logic is reversed, i.e. in order to have EFI vars support we do want:
`# CONFIG_EFI_DISABLE_RUNTIME is not set`

CONFIG_EFI_VARS was removed upstream by commit 0f5b2c69a4cbe4166ca24b76d5ada98ed2867741 ("efi: vars: Remove deprecated 'efivars' sysfs interface").
I believe the replacement is CONFIG_EFIVAR_FS which is enabled in our config:

```
admin@NI-PXIe-8880-03095FC1:~# uname -a
Linux NI-PXIe-8880-03095FC1 6.0.0-rc6-rt9-00084-g145e8921120b #1 SMP PREEMPT_RT Mon Sep 19 17:49:12 CDT 2022 x86_64 x86_64 x86_64 GNU/Linux
admin@NI-PXIe-8880-03095FC1:~# zcat /proc/config.gz | grep -E "EFIVAR|EFI_VARS"
CONFIG_EFI_VARS_PSTORE=y
# CONFIG_EFI_VARS_PSTORE_DEFAULT_DISABLE is not set
CONFIG_EFIVAR_FS=y

```

**Comment by gratian** [comment]
Changes since V1:

- disabled: CONFIG_CONTEXT_TRACKING_USER_FORCE and CONFIG_RCU_NOCB_CPU_CB_BOOST
- enabled: CONFIG_RCU_NOCB_CPU_DEFAULT_ALL

in nati_x86_64_defconfig based on '.config' audit.

**Review by bstreiff — APPROVED** [review]

**Comment by gratian** [comment]
Submitted as nilrt/master/6.0.

**Pull request closed without merging**
