### PR TITLE
Merge tag 'v6.1.46-rt13' into nilrt/master/6.1

### PR DESCRIPTION
**Pull request by xhuff**
This is a regular stable merge of latest linux-stable tag v6.1.46-rt13.

[AB#2395764](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2395764)

No merge conflicts encountered.

Testing

* [x] boot tested on cRIO-9058
* [x] re-versioned NI drivers on cRIO-9058 via dkms autoinstall and verified there are no errors.

Additional functional and performance testing will be handle by ATSs.

@ni/rtos

### CODE REVIEW

**Review by chaitu236 — APPROVED** [review]

**Comment by gratian** [comment]
I want to take a closer look before we merge this tag, Paul Gortmaker noticed there's something weird with the upload: https://lore.kernel.org/linux-rt-users/ZN%2Ff7T8hoLzKLmnr@windriver.com/

**Comment by xhuff** [comment]
> I want to take a closer look before we merge this tag, Paul Gortmaker noticed there's something weird with the upload: https://lore.kernel.org/linux-rt-users/ZN%2Ff7T8hoLzKLmnr@windriver.com/

Hmm, it appears that concern was emailed nearly a month ago with no reply...

**Comment by xhuff** [comment]
> I want to take a closer look before we merge this tag, Paul Gortmaker noticed there's something weird with the upload: https://lore.kernel.org/linux-rt-users/ZN%2Ff7T8hoLzKLmnr@windriver.com/

@gratian if you'd prefer, I can abandon this PR/work and we can simply try again with the latest tag in October

**Review by gratian — APPROVED** [review]
@xhuff Looks good. Sorry for the delay.
I've checked against stable in case the stable-rt merge was bad - nothing looks out of the ordinary.

@bstreiff I think we can merge this into `nilrt/master/6.1`. We should leave the `23.8` branches alone so we don't invalidate testing.

**Comment by xhuff** [comment]
## V2

I remerged 6.1.46-rt13 against the latest `nilrt/master/6.1` and force-pushed to my fork

FYI @bstreiff

**Comment by xhuff** [comment]
## V3
Remerge once more to pick up a missing commit

FYI @bstreiff

**Review by bstreiff — APPROVED** [review]

**Pull request merged**
